# Linux Build Configuration for Travis

language: cpp

os:
  - linux
    #  - osx

# Use Ubuntu 14.04 LTS (Trusty) as the Linux testing environment.
sudo: required
dist: trusty

env:
  - DXC_BUILD_TYPE=Release
  - DXC_BUILD_TYPE=Debug

compiler:
  - clang
  - gcc

cache:
  apt: true

git:
  depth: 1

branches:
  only:
    - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - g++-6

before_script:
  - git submodule update --init
  - if [ ${CC} = gcc ]; then CC=gcc-6; CXX=g++-6; fi

script:
  - mkdir build && cd build
  - python ../utils/linuxBuild.py --profile ${DXC_BUILD_TYPE} -GNinja --cc ${CC} --cxx ${CXX} .. .
  - ninja dxc
  - ./bin/dxc --help
  - ./bin/dxc -T ps_6_0 ../tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv
  - ./bin/dxc -T ps_6_0 ../tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv -spirv
